### ISSUE TITLE
Nazi's?

### ISSUE THREAD

**Issue by Terisback** [deepgrace/tetris#2]
![image](https://user-images.githubusercontent.com/26527529/75379780-c5fbc780-58f7-11ea-9f61-9dbccefe3a6e.png)

**Comment by Banana090** [comment]
Цвэточки

**Comment by Banana090** [comment]
ЦВЭТОЧКИ ФАШИСТОВ!

**Comment by deepgrace** [comment]
No, it's not Nazi's,  just an interesting shape, it looks like a windmill.
Just for fun!

**Comment by Terisback** [comment]
k
